Changed user to nginx

diff --git a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
--- a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
+++ b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 # Fixes this container so that Nginx is running as the nginx user.
-service nginx stop
-sed -i 's/^user.*/user nginx;/' /etc/nginx/nginx.conf
+if ! service nginx stop; then
+    echo "Failed to stop Nginx."
+    exit 1
+fi
+
+if ! grep -q '^\s*user' /etc/nginx/nginx.conf; then
+    sed -i '1i user nginx;' /etc/nginx/nginx.conf
+fi
+
 sed -i 's/\(listen[[:space:]]\+\)80;/\18080;/' /etc/nginx/sites-available/default
-service nginx start
+sudo service nginx restart
